version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: America/Los_Angeles
    labels:
      - "automerge"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "cbindgen"
